version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'watchers'
      MYSQL_USER: 'watchers_admin'
      MYSQL_PASSWORD: 'watchers_admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    expose:
      - '8000'
    links:
      - db
    depends_on:
      - db
