server:
  port: 8000

spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://db:3306/watchers?useSSL=false
    username: watchers_admin
    password: watchers_admin
    driver-class-name: com.mysql.jdbc.Driver

#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#      hibernate: DEBUG
